### ISSUE TITLE
生成的css文件里对雪碧图的引用相对路径问题

### ISSUE THREAD

**Issue by fromIRIS** [roninliu/gulp-spriter#2]
雪碧图的导出地址 跟最后生成的css文件里的背景图片的引用地址有做处理吗？ 我这边有情况就是这两个地址不相符。图片引用路径不对。

**Comment by lanpangzhi** [comment]
我也碰见了，你解决了吗

**Comment by fromIRIS** [comment]
解决了 @jilei786  看我的版本https://github.com/fromIRIS/gulp-spriter
